name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -- uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: build-app
        with:
          sdk-channel: release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: midea-ac-remote-fap
          path: ${{ steps.build-app.outputs.fap-artifacts }}
